# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b87e898004b1d748618b3b2c6c506f3fbde2fdc8b7434f13fe35803a4742d39a5c7dc36b4cd07a5614b72807cc87ca7cea29d03c2e44da045acadfd1274b220

test:
  secret_key_base: b054dac3c29515e0ac90b6661b0cd9fe962957c38d5eb840b83b190f674eb43e5b2b0224b96ffe1fcba6259548b0801b1d6aa7c55a1ea59c93b18048915502b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
